### ISSUE TITLE
Explore call number browse and bringing in visual/information

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/discovery#73]
Current item view shows call number browse as link on the item view page.  Can we expand this to resemble our mockups which incorporate both a visual for the items as well as related subjects and/or related call number information?  There may be other approaches/directions for implementing this work.

**Comment by hudajkhan** [comment]
https://projects.invisionapp.com/share/BPR5YC0CX2M#/screens/384656075  Mockups
Call number browse example (based on SearchWorks + related subject headings): https://projects.invisionapp.com/share/BPR5YC0CX2M#/screens/385291104

**Comment by tworrall** [comment]
Call number browse was mostly completed -- mostly, because there is an issue in retrieving additional records to browse. In some cases there are multiple copies of the same work, and in others there are multiple works that share the same call number (e.g., PN1.) In both cases the query that fetches additional works to browse will keep returning the same works. This happens because a query on any of those PN1 works, or any of the multiple copies, always returns the first one.

There are possibly a couple of ways to get around this issue, but there wasn't time to explore them within the BAM time frame. It would be worth pursuing after SMASH is done because this type of browse holds a lot of promise -- not just in terms of browsing call numbers, but browsing works by an author or works on a subject.
